name: lamafia
favicon: null
layout_spectrum: 0.8536512376740575
typography_spectrum: 0.6018358026631176
title: La Mafia Oficial
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5625
  lightness: 0.484200012171641
  saturation: 0.7303862036205828
  rhythmicContrast: 1
purpose: []
